### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/fieldset#34]
- [ ] Cleaning up duplicated code
- [ ] Getting test coverage up
- [ ] Logical restructure of elements #33 
- [ ] Improve bootstrap renderer #23
- [ ] Cleaning up Builder (interface)
